import Container from "@/components/Container";
import MyButton from "@/components/MyButton";
import MyInput from "@/components/MyInput";
import Repository from "@/components/Repository";
import Title from "@/components/Title";
import { RepoSearchResultItem } from "@/networking/githubTypes";
import { useState } from "react";
import { FlatList, Text } from "react-native";

export default function RepositorySearch() {

    const [repositories, setRepositories] = useState<RepoSearchResultItem[]>(exampleRepositories);
    const [keyword, setKeyword] = useState("");

    return <Container>
        <Title>Repository search</Title>

        <MyInput onChangeText={setKeyword} value={keyword} />
        <MyButton onPress={() => { }}>Search 🔍</MyButton>

        <FlatList
            ListEmptyComponent={<Text>No results</Text>}
            data={repositories}
            renderItem={({ item }) => <Repository repo={item} />}
        />
    </Container>
}


const exampleRepositories: RepoSearchResultItem[] = [{
    "id": 10270250,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==",
    "name": "react",
    "full_name": "facebook/react",
    "private": false,
    "owner": {
        "login": "facebook",
        "id": 69631,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
        "avatar_url": "https://avatars.githubusercontent.com/u/69631?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/facebook",
        "html_url": "https://github.com/facebook",
        "followers_url": "https://api.github.com/users/facebook/followers",
        "following_url": "https://api.github.com/users/facebook/following{/other_user}",
        "gists_url": "https://api.github.com/users/facebook/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/facebook/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/facebook/subscriptions",
        "organizations_url": "https://api.github.com/users/facebook/orgs",
        "repos_url": "https://api.github.com/users/facebook/repos",
        "events_url": "https://api.github.com/users/facebook/events{/privacy}",
        "received_events_url": "https://api.github.com/users/facebook/received_events",
        "type": "Organization",
        "user_view_type": "public",
        "site_admin": false
    },
    "html_url": "https://github.com/facebook/react",
    "description": "The library for web and native user interfaces.",
    "fork": false,
    "url": "https://api.github.com/repos/facebook/react",
    "forks_url": "https://api.github.com/repos/facebook/react/forks",
    "keys_url": "https://api.github.com/repos/facebook/react/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/facebook/react/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/facebook/react/teams",
    "hooks_url": "https://api.github.com/repos/facebook/react/hooks",
    "issue_events_url": "https://api.github.com/repos/facebook/react/issues/events{/number}",
    "events_url": "https://api.github.com/repos/facebook/react/events",
    "assignees_url": "https://api.github.com/repos/facebook/react/assignees{/user}",
    "branches_url": "https://api.github.com/repos/facebook/react/branches{/branch}",
    "tags_url": "https://api.github.com/repos/facebook/react/tags",
    "blobs_url": "https://api.github.com/repos/facebook/react/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/facebook/react/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/facebook/react/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/facebook/react/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/facebook/react/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/facebook/react/languages",
    "stargazers_url": "https://api.github.com/repos/facebook/react/stargazers",
    "contributors_url": "https://api.github.com/repos/facebook/react/contributors",
    "subscribers_url": "https://api.github.com/repos/facebook/react/subscribers",
    "subscription_url": "https://api.github.com/repos/facebook/react/subscription",
    "commits_url": "https://api.github.com/repos/facebook/react/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/facebook/react/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/facebook/react/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/facebook/react/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/facebook/react/contents/{+path}",
    "compare_url": "https://api.github.com/repos/facebook/react/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/facebook/react/merges",
    "archive_url": "https://api.github.com/repos/facebook/react/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/facebook/react/downloads",
    "issues_url": "https://api.github.com/repos/facebook/react/issues{/number}",
    "pulls_url": "https://api.github.com/repos/facebook/react/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/facebook/react/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/facebook/react/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/facebook/react/labels{/name}",
    "releases_url": "https://api.github.com/repos/facebook/react/releases{/id}",
    "deployments_url": "https://api.github.com/repos/facebook/react/deployments",
    "created_at": "2013-05-24T16:15:54Z",
    "updated_at": "2025-09-08T09:42:12Z",
    "pushed_at": "2025-09-08T09:42:04Z",
    "git_url": "git://github.com/facebook/react.git",
    "ssh_url": "git@github.com:facebook/react.git",
    "clone_url": "https://github.com/facebook/react.git",
    "svn_url": "https://github.com/facebook/react",
    "homepage": "https://react.dev",
    "size": 1119655,
    "stargazers_count": 238742,
    "watchers_count": 238742,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 49284,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1047,
    "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
        "declarative",
        "frontend",
        "javascript",
        "library",
        "react",
        "ui"
    ],
    "visibility": "public",
    "forks": 49284,
    "open_issues": 1047,
    "watchers": 238742,
    "default_branch": "main",
    "score": 1.0
},
{
    "id": 135786093,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMzU3ODYwOTM=",
    "name": "react",
    "full_name": "typescript-cheatsheets/react",
    "private": false,
    "owner": {
        "login": "typescript-cheatsheets",
        "id": 50188264,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjUwMTg4MjY0",
        "avatar_url": "https://avatars.githubusercontent.com/u/50188264?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/typescript-cheatsheets",
        "html_url": "https://github.com/typescript-cheatsheets",
        "followers_url": "https://api.github.com/users/typescript-cheatsheets/followers",
        "following_url": "https://api.github.com/users/typescript-cheatsheets/following{/other_user}",
        "gists_url": "https://api.github.com/users/typescript-cheatsheets/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/typescript-cheatsheets/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/typescript-cheatsheets/subscriptions",
        "organizations_url": "https://api.github.com/users/typescript-cheatsheets/orgs",
        "repos_url": "https://api.github.com/users/typescript-cheatsheets/repos",
        "events_url": "https://api.github.com/users/typescript-cheatsheets/events{/privacy}",
        "received_events_url": "https://api.github.com/users/typescript-cheatsheets/received_events",
        "type": "Organization",
        "user_view_type": "public",
        "site_admin": false
    },
    "html_url": "https://github.com/typescript-cheatsheets/react",
    "description": "Cheatsheets for experienced React developers getting started with TypeScript",
    "fork": false,
    "url": "https://api.github.com/repos/typescript-cheatsheets/react",
    "forks_url": "https://api.github.com/repos/typescript-cheatsheets/react/forks",
    "keys_url": "https://api.github.com/repos/typescript-cheatsheets/react/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/typescript-cheatsheets/react/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/typescript-cheatsheets/react/teams",
    "hooks_url": "https://api.github.com/repos/typescript-cheatsheets/react/hooks",
    "issue_events_url": "https://api.github.com/repos/typescript-cheatsheets/react/issues/events{/number}",
    "events_url": "https://api.github.com/repos/typescript-cheatsheets/react/events",
    "assignees_url": "https://api.github.com/repos/typescript-cheatsheets/react/assignees{/user}",
    "branches_url": "https://api.github.com/repos/typescript-cheatsheets/react/branches{/branch}",
    "tags_url": "https://api.github.com/repos/typescript-cheatsheets/react/tags",
    "blobs_url": "https://api.github.com/repos/typescript-cheatsheets/react/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/typescript-cheatsheets/react/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/typescript-cheatsheets/react/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/typescript-cheatsheets/react/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/typescript-cheatsheets/react/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/typescript-cheatsheets/react/languages",
    "stargazers_url": "https://api.github.com/repos/typescript-cheatsheets/react/stargazers",
    "contributors_url": "https://api.github.com/repos/typescript-cheatsheets/react/contributors",
    "subscribers_url": "https://api.github.com/repos/typescript-cheatsheets/react/subscribers",
    "subscription_url": "https://api.github.com/repos/typescript-cheatsheets/react/subscription",
    "commits_url": "https://api.github.com/repos/typescript-cheatsheets/react/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/typescript-cheatsheets/react/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/typescript-cheatsheets/react/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/typescript-cheatsheets/react/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/typescript-cheatsheets/react/contents/{+path}",
    "compare_url": "https://api.github.com/repos/typescript-cheatsheets/react/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/typescript-cheatsheets/react/merges",
    "archive_url": "https://api.github.com/repos/typescript-cheatsheets/react/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/typescript-cheatsheets/react/downloads",
    "issues_url": "https://api.github.com/repos/typescript-cheatsheets/react/issues{/number}",
    "pulls_url": "https://api.github.com/repos/typescript-cheatsheets/react/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/typescript-cheatsheets/react/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/typescript-cheatsheets/react/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/typescript-cheatsheets/react/labels{/name}",
    "releases_url": "https://api.github.com/repos/typescript-cheatsheets/react/releases{/id}",
    "deployments_url": "https://api.github.com/repos/typescript-cheatsheets/react/deployments",
    "created_at": "2018-06-02T04:08:16Z",
    "updated_at": "2025-09-08T08:36:46Z",
    "pushed_at": "2025-08-23T05:09:07Z",
    "git_url": "git://github.com/typescript-cheatsheets/react.git",
    "ssh_url": "git@github.com:typescript-cheatsheets/react.git",
    "clone_url": "https://github.com/typescript-cheatsheets/react.git",
    "svn_url": "https://github.com/typescript-cheatsheets/react",
    "homepage": "https://react-typescript-cheatsheet.netlify.app",
    "size": 3192,
    "stargazers_count": 46597,
    "watchers_count": 46597,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": true,
    "forks_count": 4241,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
        "cheatsheet",
        "guide",
        "react",
        "typescript"
    ],
    "visibility": "public",
    "forks": 4241,
    "open_issues": 1,
    "watchers": 46597,
    "default_branch": "main",
    "score": 1.0
},
{
    "id": 75396575,
    "node_id": "MDEwOlJlcG9zaXRvcnk3NTM5NjU3NQ==",
    "name": "react",
    "full_name": "duxianwei520/react",
    "private": false,
    "owner": {
        "login": "duxianwei520",
        "id": 3249653,
        "node_id": "MDQ6VXNlcjMyNDk2NTM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3249653?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/duxianwei520",
        "html_url": "https://github.com/duxianwei520",
        "followers_url": "https://api.github.com/users/duxianwei520/followers",
        "following_url": "https://api.github.com/users/duxianwei520/following{/other_user}",
        "gists_url": "https://api.github.com/users/duxianwei520/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/duxianwei520/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/duxianwei520/subscriptions",
        "organizations_url": "https://api.github.com/users/duxianwei520/orgs",
        "repos_url": "https://api.github.com/users/duxianwei520/repos",
        "events_url": "https://api.github.com/users/duxianwei520/events{/privacy}",
        "received_events_url": "https://api.github.com/users/duxianwei520/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
    },
    "html_url": "https://github.com/duxianwei520/react",
    "description": " React+webpack+redux+ant design+axios+less全家桶后台管理框架",
    "fork": false,
    "url": "https://api.github.com/repos/duxianwei520/react",
    "forks_url": "https://api.github.com/repos/duxianwei520/react/forks",
    "keys_url": "https://api.github.com/repos/duxianwei520/react/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/duxianwei520/react/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/duxianwei520/react/teams",
    "hooks_url": "https://api.github.com/repos/duxianwei520/react/hooks",
    "issue_events_url": "https://api.github.com/repos/duxianwei520/react/issues/events{/number}",
    "events_url": "https://api.github.com/repos/duxianwei520/react/events",
    "assignees_url": "https://api.github.com/repos/duxianwei520/react/assignees{/user}",
    "branches_url": "https://api.github.com/repos/duxianwei520/react/branches{/branch}",
    "tags_url": "https://api.github.com/repos/duxianwei520/react/tags",
    "blobs_url": "https://api.github.com/repos/duxianwei520/react/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/duxianwei520/react/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/duxianwei520/react/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/duxianwei520/react/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/duxianwei520/react/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/duxianwei520/react/languages",
    "stargazers_url": "https://api.github.com/repos/duxianwei520/react/stargazers",
    "contributors_url": "https://api.github.com/repos/duxianwei520/react/contributors",
    "subscribers_url": "https://api.github.com/repos/duxianwei520/react/subscribers",
    "subscription_url": "https://api.github.com/repos/duxianwei520/react/subscription",
    "commits_url": "https://api.github.com/repos/duxianwei520/react/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/duxianwei520/react/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/duxianwei520/react/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/duxianwei520/react/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/duxianwei520/react/contents/{+path}",
    "compare_url": "https://api.github.com/repos/duxianwei520/react/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/duxianwei520/react/merges",
    "archive_url": "https://api.github.com/repos/duxianwei520/react/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/duxianwei520/react/downloads",
    "issues_url": "https://api.github.com/repos/duxianwei520/react/issues{/number}",
    "pulls_url": "https://api.github.com/repos/duxianwei520/react/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/duxianwei520/react/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/duxianwei520/react/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/duxianwei520/react/labels{/name}",
    "releases_url": "https://api.github.com/repos/duxianwei520/react/releases{/id}",
    "deployments_url": "https://api.github.com/repos/duxianwei520/react/deployments",
    "created_at": "2016-12-02T13:08:43Z",
    "updated_at": "2025-09-06T10:17:32Z",
    "pushed_at": "2024-06-20T19:02:50Z",
    "git_url": "git://github.com/duxianwei520/react.git",
    "ssh_url": "git@github.com:duxianwei520/react.git",
    "clone_url": "https://github.com/duxianwei520/react.git",
    "svn_url": "https://github.com/duxianwei520/react",
    "homepage": "",
    "size": 2836,
    "stargazers_count": 5216,
    "watchers_count": 5216,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 1783,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 25,
    "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
        "ant-design-pro",
        "antd",
        "babel",
        "es6",
        "es7",
        "react",
        "redux",
        "webpack"
    ],
    "visibility": "public",
    "forks": 1783,
    "open_issues": 25,
    "watchers": 5216,
    "default_branch": "master",
    "score": 1.0
},
{
    "id": 121814210,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMjE4MTQyMTA=",
    "name": "react",
    "full_name": "primer/react",
    "private": false,
    "owner": {
        "login": "primer",
        "id": 7143434,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjcxNDM0MzQ=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7143434?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/primer",
        "html_url": "https://github.com/primer",
        "followers_url": "https://api.github.com/users/primer/followers",
        "following_url": "https://api.github.com/users/primer/following{/other_user}",
        "gists_url": "https://api.github.com/users/primer/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/primer/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/primer/subscriptions",
        "organizations_url": "https://api.github.com/users/primer/orgs",
        "repos_url": "https://api.github.com/users/primer/repos",
        "events_url": "https://api.github.com/users/primer/events{/privacy}",
        "received_events_url": "https://api.github.com/users/primer/received_events",
        "type": "Organization",
        "user_view_type": "public",
        "site_admin": false
    },
    "html_url": "https://github.com/primer/react",
    "description": "An implementation of GitHub's Primer Design System using React",
    "fork": false,
    "url": "https://api.github.com/repos/primer/react",
    "forks_url": "https://api.github.com/repos/primer/react/forks",
    "keys_url": "https://api.github.com/repos/primer/react/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/primer/react/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/primer/react/teams",
    "hooks_url": "https://api.github.com/repos/primer/react/hooks",
    "issue_events_url": "https://api.github.com/repos/primer/react/issues/events{/number}",
    "events_url": "https://api.github.com/repos/primer/react/events",
    "assignees_url": "https://api.github.com/repos/primer/react/assignees{/user}",
    "branches_url": "https://api.github.com/repos/primer/react/branches{/branch}",
    "tags_url": "https://api.github.com/repos/primer/react/tags",
    "blobs_url": "https://api.github.com/repos/primer/react/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/primer/react/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/primer/react/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/primer/react/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/primer/react/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/primer/react/languages",
    "stargazers_url": "https://api.github.com/repos/primer/react/stargazers",
    "contributors_url": "https://api.github.com/repos/primer/react/contributors",
    "subscribers_url": "https://api.github.com/repos/primer/react/subscribers",
    "subscription_url": "https://api.github.com/repos/primer/react/subscription",
    "commits_url": "https://api.github.com/repos/primer/react/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/primer/react/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/primer/react/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/primer/react/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/primer/react/contents/{+path}",
    "compare_url": "https://api.github.com/repos/primer/react/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/primer/react/merges",
    "archive_url": "https://api.github.com/repos/primer/react/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/primer/react/downloads",
    "issues_url": "https://api.github.com/repos/primer/react/issues{/number}",
    "pulls_url": "https://api.github.com/repos/primer/react/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/primer/react/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/primer/react/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/primer/react/labels{/name}",
    "releases_url": "https://api.github.com/repos/primer/react/releases{/id}",
    "deployments_url": "https://api.github.com/repos/primer/react/deployments",
    "created_at": "2018-02-17T00:09:05Z",
    "updated_at": "2025-09-08T03:13:38Z",
    "pushed_at": "2025-09-08T07:27:55Z",
    "git_url": "git://github.com/primer/react.git",
    "ssh_url": "git@github.com:primer/react.git",
    "clone_url": "https://github.com/primer/react.git",
    "svn_url": "https://github.com/primer/react",
    "homepage": "https://primer.style/product/getting-started/react/",
    "size": 416258,
    "stargazers_count": 3658,
    "watchers_count": 3658,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": true,
    "has_discussions": true,
    "forks_count": 627,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 156,
    "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
        "component-library",
        "design-system",
        "primer",
        "react"
    ],
    "visibility": "public",
    "forks": 627,
    "open_issues": 156,
    "watchers": 3658,
    "default_branch": "main",
    "score": 1.0
},
{
    "id": 90759930,
    "node_id": "MDEwOlJlcG9zaXRvcnk5MDc1OTkzMA==",
    "name": "react",
    "full_name": "discountry/react",
    "private": false,
    "owner": {
        "login": "discountry",
        "id": 4507101,
        "node_id": "MDQ6VXNlcjQ1MDcxMDE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4507101?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/discountry",
        "html_url": "https://github.com/discountry",
        "followers_url": "https://api.github.com/users/discountry/followers",
        "following_url": "https://api.github.com/users/discountry/following{/other_user}",
        "gists_url": "https://api.github.com/users/discountry/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/discountry/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/discountry/subscriptions",
        "organizations_url": "https://api.github.com/users/discountry/orgs",
        "repos_url": "https://api.github.com/users/discountry/repos",
        "events_url": "https://api.github.com/users/discountry/events{/privacy}",
        "received_events_url": "https://api.github.com/users/discountry/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
    },
    "html_url": "https://github.com/discountry/react",
    "description": "React docs in Chinese | React 中文文档翻译",
    "fork": false,
    "url": "https://api.github.com/repos/discountry/react",
    "forks_url": "https://api.github.com/repos/discountry/react/forks",
    "keys_url": "https://api.github.com/repos/discountry/react/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/discountry/react/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/discountry/react/teams",
    "hooks_url": "https://api.github.com/repos/discountry/react/hooks",
    "issue_events_url": "https://api.github.com/repos/discountry/react/issues/events{/number}",
    "events_url": "https://api.github.com/repos/discountry/react/events",
    "assignees_url": "https://api.github.com/repos/discountry/react/assignees{/user}",
    "branches_url": "https://api.github.com/repos/discountry/react/branches{/branch}",
    "tags_url": "https://api.github.com/repos/discountry/react/tags",
    "blobs_url": "https://api.github.com/repos/discountry/react/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/discountry/react/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/discountry/react/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/discountry/react/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/discountry/react/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/discountry/react/languages",
    "stargazers_url": "https://api.github.com/repos/discountry/react/stargazers",
    "contributors_url": "https://api.github.com/repos/discountry/react/contributors",
    "subscribers_url": "https://api.github.com/repos/discountry/react/subscribers",
    "subscription_url": "https://api.github.com/repos/discountry/react/subscription",
    "commits_url": "https://api.github.com/repos/discountry/react/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/discountry/react/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/discountry/react/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/discountry/react/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/discountry/react/contents/{+path}",
    "compare_url": "https://api.github.com/repos/discountry/react/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/discountry/react/merges",
    "archive_url": "https://api.github.com/repos/discountry/react/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/discountry/react/downloads",
    "issues_url": "https://api.github.com/repos/discountry/react/issues{/number}",
    "pulls_url": "https://api.github.com/repos/discountry/react/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/discountry/react/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/discountry/react/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/discountry/react/labels{/name}",
    "releases_url": "https://api.github.com/repos/discountry/react/releases{/id}",
    "deployments_url": "https://api.github.com/repos/discountry/react/deployments",
    "created_at": "2017-05-09T15:09:00Z",
    "updated_at": "2025-09-08T01:50:33Z",
    "pushed_at": "2025-06-12T03:13:39Z",
    "git_url": "git://github.com/discountry/react.git",
    "ssh_url": "git@github.com:discountry/react.git",
    "clone_url": "https://github.com/discountry/react.git",
    "svn_url": "https://github.com/discountry/react",
    "homepage": "https://zh-hans.react.dev/",
    "size": 34996,
    "stargazers_count": 1326,
    "watchers_count": 1326,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 555,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 43,
    "license": {
        "key": "cc-by-4.0",
        "name": "Creative Commons Attribution 4.0 International",
        "spdx_id": "CC-BY-4.0",
        "url": "https://api.github.com/licenses/cc-by-4.0",
        "node_id": "MDc6TGljZW5zZTI1"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
        "docs",
        "react"
    ],
    "visibility": "public",
    "forks": 555,
    "open_issues": 43,
    "watchers": 1326,
    "default_branch": "master",
    "score": 1.0
},
{
    "id": 77513419,
    "node_id": "MDEwOlJlcG9zaXRvcnk3NzUxMzQxOQ==",
    "name": "react",
    "full_name": "react-redux-antd-es6/react",
    "private": false,
    "owner": {
        "login": "react-redux-antd-es6",
        "id": 24805142,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjI0ODA1MTQy",
        "avatar_url": "https://avatars.githubusercontent.com/u/24805142?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/react-redux-antd-es6",
        "html_url": "https://github.com/react-redux-antd-es6",
        "followers_url": "https://api.github.com/users/react-redux-antd-es6/followers",
        "following_url": "https://api.github.com/users/react-redux-antd-es6/following{/other_user}",
        "gists_url": "https://api.github.com/users/react-redux-antd-es6/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/react-redux-antd-es6/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/react-redux-antd-es6/subscriptions",
        "organizations_url": "https://api.github.com/users/react-redux-antd-es6/orgs",
        "repos_url": "https://api.github.com/users/react-redux-antd-es6/repos",
        "events_url": "https://api.github.com/users/react-redux-antd-es6/events{/privacy}",
        "received_events_url": "https://api.github.com/users/react-redux-antd-es6/received_events",
        "type": "Organization",
        "user_view_type": "public",
        "site_admin": false
    },
    "html_url": "https://github.com/react-redux-antd-es6/react",
    "description": "基于react的企业后台管理开发框架",
    "fork": false,
    "url": "https://api.github.com/repos/react-redux-antd-es6/react",
    "forks_url": "https://api.github.com/repos/react-redux-antd-es6/react/forks",
    "keys_url": "https://api.github.com/repos/react-redux-antd-es6/react/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/react-redux-antd-es6/react/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/react-redux-antd-es6/react/teams",
    "hooks_url": "https://api.github.com/repos/react-redux-antd-es6/react/hooks",
    "issue_events_url": "https://api.github.com/repos/react-redux-antd-es6/react/issues/events{/number}",
    "events_url": "https://api.github.com/repos/react-redux-antd-es6/react/events",
    "assignees_url": "https://api.github.com/repos/react-redux-antd-es6/react/assignees{/user}",
    "branches_url": "https://api.github.com/repos/react-redux-antd-es6/react/branches{/branch}",
    "tags_url": "https://api.github.com/repos/react-redux-antd-es6/react/tags",
    "blobs_url": "https://api.github.com/repos/react-redux-antd-es6/react/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/react-redux-antd-es6/react/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/react-redux-antd-es6/react/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/react-redux-antd-es6/react/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/react-redux-antd-es6/react/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/react-redux-antd-es6/react/languages",
    "stargazers_url": "https://api.github.com/repos/react-redux-antd-es6/react/stargazers",
    "contributors_url": "https://api.github.com/repos/react-redux-antd-es6/react/contributors",
    "subscribers_url": "https://api.github.com/repos/react-redux-antd-es6/react/subscribers",
    "subscription_url": "https://api.github.com/repos/react-redux-antd-es6/react/subscription",
    "commits_url": "https://api.github.com/repos/react-redux-antd-es6/react/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/react-redux-antd-es6/react/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/react-redux-antd-es6/react/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/react-redux-antd-es6/react/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/react-redux-antd-es6/react/contents/{+path}",
    "compare_url": "https://api.github.com/repos/react-redux-antd-es6/react/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/react-redux-antd-es6/react/merges",
    "archive_url": "https://api.github.com/repos/react-redux-antd-es6/react/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/react-redux-antd-es6/react/downloads",
    "issues_url": "https://api.github.com/repos/react-redux-antd-es6/react/issues{/number}",
    "pulls_url": "https://api.github.com/repos/react-redux-antd-es6/react/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/react-redux-antd-es6/react/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/react-redux-antd-es6/react/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/react-redux-antd-es6/react/labels{/name}",
    "releases_url": "https://api.github.com/repos/react-redux-antd-es6/react/releases{/id}",
    "deployments_url": "https://api.github.com/repos/react-redux-antd-es6/react/deployments",
    "created_at": "2016-12-28T07:44:04Z",
    "updated_at": "2025-09-05T08:41:20Z",
    "pushed_at": "2024-03-17T01:32:30Z",
    "git_url": "git://github.com/react-redux-antd-es6/react.git",
    "ssh_url": "git@github.com:react-redux-antd-es6/react.git",
    "clone_url": "https://github.com/react-redux-antd-es6/react.git",
    "svn_url": "https://github.com/react-redux-antd-es6/react",
    "homepage": "",
    "size": 43796,
    "stargazers_count": 1243,
    "watchers_count": 1243,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 482,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 16,
    "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
        "antd",
        "react",
        "webpack"
    ],
    "visibility": "public",
    "forks": 482,
    "open_issues": 16,
    "watchers": 1243,
    "default_branch": "master",
    "score": 1.0
}
]
